### ISSUE TITLE
[detalle-cliente] No hay un pleaceholder de imagenes por default

### ISSUE THREAD

**Issue by smpiano** [smpiano/7547-tdp2-1c#9]
Pasos para ejecutar el problema:
1. Acceder a la app
2. Desplegar el menu
3. Ir a off-road
4. Listar los clientes
5. Ir al detalle del cliente

Severidad 5

**Comment by tario** [comment]
Esta bien que lo reportaste, pero no convenia usar targetprocess ?

**Comment by encubos** [comment]
Fua pasado a TP, vamos a probar usar los bugs desde la otra herramienta
